title: Welcome to my Page
author: Tony Le
email: tonyle.1537@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my site. More coming later.

# social links
github_username:  Tonneh # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
